name: 'coswarmup_restart'
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0.001

scheduler:
  _target_: transformers.optimization.get_cosine_with_hard_restarts_schedule_with_warmup
  num_cycles: 5

